name: main

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - uses: actions/checkout@v3

      # Set up Composer
      - uses: php-actions/composer@v6

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run gulp build task
        run: ./node_modules/gulp/bin/gulp.js build

      - name: Sync
        env:
          dest: "rainbowhealth@34.66.217.167:/sites/rainbowhealth.org/files/wp-content/themes/justus-health"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /README.md \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
